export default async function writing(yo) {
  yo.fs.copyTpl(
    yo.templatePath('template/shared/src/**'),
    yo.destinationPath('src'),
    yo.context
  );
  yo.fs.copyTpl(
    yo.templatePath('template/shared/prisma/**'),
    yo.destinationPath('prisma'),
    yo.context
  );
  yo.fs.copyTpl(
    yo.templatePath('template/shared/docker/**'),
    yo.destinationPath('docker'),
    yo.context
  );
  yo.fs.copyTpl(
    yo.templatePath('template/shared/tests'),
    yo.destinationPath('tests'),
    yo.context
  );
  yo.fs.copy(
    yo.templatePath('template/shared/views/**'),
    yo.destinationPath('views')
  );
  yo.fs.copyTpl(
    yo.templatePath('template/shared/_package.json'),
    yo.destinationPath('package.json'),
    yo.context
  );
  yo.fs.copy(
    yo.templatePath('template/shared/_eslintrc'),
    yo.destinationPath('.eslintrc')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/Makefile'),
    yo.destinationPath('Makefile')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/_babelrc'),
    yo.destinationPath('.babelrc')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/_cspellrc'),
    yo.destinationPath('.cspellrc')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/_gitignore'),
    yo.destinationPath('.gitignore')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/tsconfig.json'),
    yo.destinationPath('tsconfig.json')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/tsconfig.build.json'),
    yo.destinationPath('tsconfig.build.json')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/silicon.mk'),
    yo.destinationPath('silicon.mk')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/_graphqlconfig'),
    yo.destinationPath('.graphqlconfig')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/example.env'),
    yo.destinationPath('example.env')
  );
  yo.fs.copy(
    yo.templatePath('template/shared/_dockerignore'),
    yo.destinationPath('.dockerignore')
  );
  if (!yo.context.lock) {
    yo.fs.copy(
      yo.templatePath('template/shared/_npmrc'),
      yo.destinationPath('.npmrc')
    );
  }
}
